### ISSUE TITLE
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 296665168 bytes) in /public_html/wp-content/plugins/do-spaces-sync/vendor/league/flysystem/src/Util/MimeType.php on line 188

### ISSUE THREAD

**Issue by yoBoss283** [bitkidd/DigitalOcean-Spaces-Sync#41] opened 2020-09-05 08:27 UTC
`Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 296665168 bytes) in /var/sites/a/domain.com/public_html/wp-content/plugins/do-spaces-sync/vendor/league/flysystem/src/Util/MimeType.php on line 188`

Hi there, we tried to upload mp3 and it returns with this error. There is no error with JPG. Also this was on a WordPress account with Editor privileges. This error does not occur when this user account was assigned Administrator privileges in Wordpress.

https://github.com/bitkidd/DigitalOcean-Spaces-Sync/blob/e1119088bfa01aaf90092d91be4dba8485eff7ed/vendor/league/flysystem/src/Util/MimeType.php#L188

**Comment by zeidanbm** [comment] 2020-09-05 16:03
The error is coming from League\Flysystem\Filesystem php vendor library and could be related to [this issue](https://github.com/thephpleague/flysystem/issues/1172).

**Comment by yoBoss283** [comment] 2020-09-05 16:33
@zeidanbm thanks for posting it there as well, you clearly have a better understanding of what is going on (not a coder here!). Also, isn't it odd that when I change it to an administrator account it doesn't give an error message (it work). Is there a memory limit or some other limit when the user 'only' has an Editor privilege?

**Comment by zeidanbm** [comment] 2020-09-05 17:37
There might be a function in wordpress that manipulates the memory limit based on roles. Just a quick search and found those [admin_memory_limit()](https://developer.wordpress.org/reference/hooks/admin_memory_limit/), [wp_raise_memory_limit()](https://developer.wordpress.org/reference/functions/wp_raise_memory_limit/)
To increase your memory limit try to edit your wp-config.php. [Check this out and it might help you.](https://wpe.approveme.com/article/101-increase-memory-limit)

Please note that increasing memory limit is not a good solution cause this usually happens because there is something wrong in the php code. If I got time next week I'll try to investigate further and test this out.

**Comment by yoBoss283** [comment] 2020-09-06 07:47
Thanks, it seems the wp_raise_memory was set to 256M (admin_memory_limit was set to 768M). The file to upload ranged between 30mb to 75mb, not sure if that made a difference. I raised the limit to 768M for now, I will need to wait whether the user experiences the same error again (on my machine it worked). 

The issue seems to be very similar to the one described here:
https://www.wpbeginner.com/wp-tutorials/fix-wordpress-memory-exhausted-error-increase-php-memory/

**Comment by VeryStrongFingers** [comment] 2021-02-14 06:56
I inadvertently found the cause of your issues via a completely separate GitHub issue https://github.com/laravel/framework/issues/36249#issuecomment-778735186

Looks to be a PHP bug derived from one of the dependencies called `libmagic`

**References**
    https://bugs.php.net/bug.php?id=78987
    https://bugs.astron.com/view.php?id=234
    https://bugs.php.net/bug.php?id=79263

you'll have to wait for it to be resolved in upstream PHP

**Closed** 2021-05-18 16:18 UTC
